# NUMPY

## 1. Creating Numpy Arrays

In [4]:
import numpy as np

In [5]:
# a. using np.array()

arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])

In [8]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [9]:
type(arr3)

numpy.ndarray

In [10]:
type(arr2)

numpy.ndarray

In [11]:
arr3 = np.ones((3,3))

In [12]:
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr3 = np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr4 = np.random.random((5,6))
arr4

array([[0.60025263, 0.86284654, 0.80918847, 0.46086903, 0.94124521,
        0.58509403],
       [0.256404  , 0.89020712, 0.10324771, 0.2507273 , 0.98511789,
        0.0249987 ],
       [0.07508597, 0.03029111, 0.84508886, 0.74394051, 0.80130724,
        0.42170374],
       [0.9573082 , 0.93682664, 0.87880164, 0.25435453, 0.67925305,
        0.77198372],
       [0.51962214, 0.95135076, 0.91612226, 0.55490373, 0.23134141,
        0.82523815]])

In [15]:
arr5 = np.linspace(1,100,10)
arr5

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [16]:
arr6 = arr5.copy()

In [17]:
arr6

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [18]:
arr7 = np.identity(5)
arr7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2. Properties/Attributes

In [19]:
arr2.shape

(2, 3)

In [20]:
arr7.shape

(5, 5)

In [21]:
arr3.shape

(10,)

In [22]:
arr2.ndim

2

In [23]:
arr3.size

10

In [24]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr4.size

30

In [26]:
arr3.itemsize

4

### 

In [27]:
arr3.dtype

dtype('int32')

In [28]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr3.astype('float')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr4

array([[0.60025263, 0.86284654, 0.80918847, 0.46086903, 0.94124521,
        0.58509403],
       [0.256404  , 0.89020712, 0.10324771, 0.2507273 , 0.98511789,
        0.0249987 ],
       [0.07508597, 0.03029111, 0.84508886, 0.74394051, 0.80130724,
        0.42170374],
       [0.9573082 , 0.93682664, 0.87880164, 0.25435453, 0.67925305,
        0.77198372],
       [0.51962214, 0.95135076, 0.91612226, 0.55490373, 0.23134141,
        0.82523815]])

In [32]:
arr3 = np.array([])

In [33]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## Arrays vs Lists

In [34]:
# In terms of memory
l = range(100)
a = np.arange(0,100)

In [35]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
import sys

In [37]:
sys.getsizeof(l[0])*len(l)

2400

In [38]:
a.itemsize*a.size

400

In [52]:
# In terms of execution time
import time
x = range(100000)
y = range(100000,200000)
start_time = time.time()
z = [(x+y) for x,y in zip(x,y)]
t1 = time.time() - start_time
print(t1)

0.027958154678344727


In [46]:
import time

In [51]:
a = np.arange(100000)
b = np.arange(100000,200000)
start_time = time.time()
c = a + b
t2 = time.time() - start_time
print(t2)

0.0


In [49]:
t1/t2

2.995852355802226

# Arrays Operations

In [41]:
np.arange(1,25).reshape(4,6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
a+=10
a

In [ ]:
a.dot(np.transpose(a))

In [ ]:
a.max(axis=1)

# Indexing and Slicing

In [ ]:
c = np.arange(10)
c

In [ ]:
c[3:6:2]

In [ ]:
a

In [ ]:
import matplotlib.pyplot as plt

In [54]:
x = np.linspace(-50,50,50)


In [ ]:
y = x*x + 2*x + 4

NameError: name 'plt' is not defined